package com.sgscq.vpn;

/* JADX INFO: This class is generated by JADX */
public final class R {

    public static final class color {
        public static final int ic_launcher_background = 0x7f010000;
    }

    public static final class drawable {
        public static final int ic_launcher_background = 0x7f020000;
        public static final int ic_launcher_foreground = 0x7f020001;
        public static final int ic_launcher_foreground_offline = 0x7f020002;
        public static final int ic_launcher_foreground_vpn = 0x7f020003;
    }

    public static final class mipmap {
        public static final int ic_launcher = 0x7f030000;
        public static final int ic_launcher_round = 0x7f030001;
    }

    public static final class raw {
        public static final int aliyun_direct_ca = 0x7f040000;
        public static final int battle_offline_permit_public_key = 0x7f040001;
    }

    public static final class string {
        public static final int app_name = 0x7f050000;
    }

    public static final class xml {
        public static final int file_paths = 0x7f060000;
        public static final int network_security_config = 0x7f060001;
    }
}
