// Approximate JavaScript reconstructed from SpiderMonkey v22 bytecode.
// This is not the original source text; unresolved regions carry TODO_BYTECODE markers.
// Embedded source: /Users/zhanglinsen/workspace/bianfeng/sgscq1-china-client/projects/sgscq/Resources/src_jsc/Cfg/String.js:1
// source line 20, bytecode pc 0
var mString;
// source line 2480, bytecode pc 1491
(mString = {
    IdCardBinding_100: {
        format: "应文化部要求，您的账户未进行实名制，为了保证您在游戏中的利益，\n充值用户必须绑定账号并且实名认证，如若未绑定账号玩家请先绑定\n账号再实名认证，如果账号用户请直接实名认证!"
    },
    IdCardBinding_101: { format: "验证手机号" },
    IdCardBinding_102: { format: "手机验证成功后可在邮箱中领取将军盏*1" },
    IdCardBinding_103: { format: "立即验证" },
    IdCardBinding_104: { format: "提醒" },
    IdCardBinding_105: { format: "亲爱的主公，您今天已经达到了充值上限。请明天再来惠顾！" },
    AwakeActiveDisable1: { format: "主公,购买条件未满足" },
    BtnTypeString: { format: "Btn_MainMenuViewBtn_Copy_$1" },
    titleStr_duiJiu: { format: "对酒" },
    BeautyTitle: { format: "红颜出巡" },
    BeautyBtnTitle1: { format: "培养$1次" },
    BeautyBtnTitle2: { format: "立即结束" },
    BeautyBtnTitle3: { format: "出巡结束" },
    BeautyBtnTitle4: { format: "出巡成功" },
    BeautyLabel1: { format: "总属性加成：" },
    BeautyLabel2: { format: "消耗灵韵:$1" },
    BeautyLabel3: { format: "获得经验:$1" },
    BeautyText1: { format: "当前" },
    BeautyText2: { format: "下一级" },
    BeautyText3: { format: "下一级天赋" },
    BeautyStatus1: { format: "时间：$1  出巡中 ..." },
    BeautyStatus2: { format: "等待出巡" },
    BeautyNoOpen: { format: "红颜出巡尚未开放，敬请期待!" },
    BeautyTips1: { format: "等级：$1" },
    BeautyTips2: { format: "下一级：" },
    BeautyTips3: { format: "红颜币：$1" },
    BeautyTips4: { format: "灵韵：$1" },
    BeautyTips7: { format: "$1：$2" },
    BeautyTips5: { format: "当前天赋已满级" },
    BeautyTips11: { format: "灵韵、灵芝" },
    BeautyTips12: { format: "、铸铁" },
    BeautyTips13: { format: "、觉醒钥匙" },
    BeautyTips14: { format: "、武将魂魄" },
    BeautyTips15: { format: "等" },
    BeautyTips8: { format: "红颜之心" },
    BeautyTips9: { format: "宝箱之心" },
    BeautyTips10: { format: "宝箱天赋" },
    BeautyContent1: { format: "您是否确定花费$1元宝立即完成此次出巡？" },
    BeautyContent2: { format: "您的其他红颜还在出巡中，请等待！" },
    BeautyContent3: { format: "此次出巡结束，请邮箱中领取出巡奖励！" },
    BeautyNoMaxStr: { format: "当前未有玩家升至满级，请各位玩家继续努力" },
    BeautyMaxStr: { format: "首个满级玩家: $1  $2" },
    BeautyErrorTxt1001: { format: "红颜币不足" },
    BeautyErrorTxt1019: { format: "红颜已满级" },
    BeautyDialog_title: { format: "红颜币兑换" },
    BuyPrompt_1: { format: "购买提示" },
    BeautyBuyPrompt_2: { format: "是否确定花$1元宝立即完成本次出巡" },
    BuyPrompt_3: { format: "主公，元宝不足" },
    BuyPrompt_4: { format: "主公，灵韵不足" },
    BuyPrompt_5: { format: "主公，红颜币不足" },
    BeautyConfirmStr: { format: "是否确定花$1红颜币兑换$2?" },
    ActivityNotOpen: { format: "不在活动时间内" },
    Lianhua: { format: "炼化" },
    SelectSkill: { format: "技能选择" },
    RefiningSkill_title: { format: "\\u70BC\\u5316$0\\u9636\\xB7$1" },
    refine_jiacheng: { format: "炼化加成" },
    refine_uptext: { format: "技能炼化进阶一阶" },
    refine_xuqiu: { format: "炼化需求" },
    RefiningSkill_needlevel: { format: "主公等级达到$1级解锁" },
    RefiningNotFill: { format: "炼化材料不足！" },
    RefiningFailed: { format: "炼化失败！" },
    titleStr_ZuiZhongXieYi: { format: "最终用户使用许可协议" },
    hintStr_ZuiZhongXieYi: { format: "用户注册必须同意最终用户使用许可协议" },
    hintStr_3rd_ZuiZhongXieYi: { format: "第三方账号授权必须同意最终用户使用许可协议" },
    titleStr_ZhuXiao: { format: "注销游戏账号" },
    content_ZhuXiao: { format: "注销游戏账号请联系客服" },
    contentStr_ZhuXiao: { format: "注销游戏账号请联系客服：\n 客服电话：\n 4007202233-3 ;\n 021-51369888 ;" },
    btnStr_ZhuXiao: { format: "注销" },
    str_specialtime: { format: "此功能暂时关闭，感谢您的支持与理解。" },
    test: { format: "" }
});
/* TODO_BYTECODE pc=1492 opcode=try reason=control_or_scope_semantics_not_structured */
// source line 2485, bytecode pc 1513
(xs.Cfg.String = mString);
