// Approximate JavaScript reconstructed from SpiderMonkey v22 bytecode.
// This is not the original source text; unresolved regions carry TODO_BYTECODE markers.
// Embedded source: /Users/zhanglinsen/workspace/bianfeng/sgscq1-china-client/projects/sgscq/Resources/src_jsc/Cfg/Url.js:1
// source line 7, bytecode pc 42
(xs.Cfg.Url = (xs.Cfg.Url || {}));
// source line 624, bytecode pc 2734
(xs.Cfg.Url = {
    FightSkillTest: "10.225.254.48:8090/sanguosha_moniqi",
    GameAddrs: [
        { name: "Develop", domain: "10.225.254.48:8090/sanguosha" },
        { name: "TestOnLine", domain: "cqzx.sanguosha.com/sanguosha_account" },
        { name: "FightSimulator", domain: "10.225.254.48:8090/sanguosha_moniqi" },
        { name: "NewApi", domain: "10.225.254.48:8090/sanguosha_new" },
        { name: "test", domain: "10.225.254.113/test/sanguosha_account" },
        { name: "OverseasTr", domain: "10.225.254.48:8090/sanguosha_traditional" },
        { name: "TestOnLine", domain: "cqzx.sanguosha.com/sanguosha_testonline" }
    ],
    DownloadAddr: "cqzx.sanguosha.com/hd_resource/",
    FightTest: "/index.php?do=battle.mnq",
    Login: "/?do=user.login",
    TestUserLogin: "/?do=user.testLogin",
    PartyReceive: "/index.php?do=activity.receive",
    PartyReceivePower: "/index.php?do=activity.receivePower",
    PartySlotMachines: "/index.php?do=activity.gamble",
    PartyDouble11: "/index.php?do=activity.exchange",
    QueueTeam: "/index.php?do=team.chgTeam",
    ChangeTeam: "/index.php?do=team.chgBattleTeam",
    EquipSkill: "/index.php?do=general.setSkill",
    EquipEquipment: "/index.php?do=general.setEquipment",
    EquipAssistant: "/index.php?do=general.setLieutenant",
    getChapterInfo: "/index.php?do=map.getUserMap",
    FightBefore: "/?do=dungeon.fightBefore",
    Fight: "/?do=dungeon.fight",
    CopyFight: "/?do=festival.goFight",
    CopyData: "/?do=festival.init",
    PlantTreeData: "/?do=festival.initRainDew",
    MultiKill: "/?do=dungeon.multiKill",
    OpenTreasureBox: "?do=dungeon.openBox",
    multiKillSpecialInfo: "?do=dungeon.multiKillSpecialInfo",
    MultiKillSpecial: "?do=dungeon.multiKillSpecial",
    Sell: "/index.php?do=equipment.sell",
    Melt: "/index.php?do=equipment.melt",
    MultMelt: "/index.php?do=equipment.multiMelt",
    EquipPieceSell: "/index.php?do=equipment.equipmentPieceSell",
    EquipPieceComposite: "/index.php?do=equipment.equipmentCompose",
    ToastInfo: "/index.php?do=wine.wineInfo",
    Toast: "/index.php?do=wine.wine",
    Alchemy: "/index.php?do=general.culture",
    TakeMedicine: "/index.php?do=general.takeCultureItem",
    GetGoodsList: "/index.php?do=item.getList",
    GetLimitGoodsList: "/index.php?do=item.getQuickList",
    BuyGoods: "/index.php?do=item.buy",
    UseItem: "/index.php?do=item.use",
    ResolveItem: "/index.php?do=item.resolveItem",
    DeleteItem: "/index.php?do=item.deleteItem",
    Synthetise: "/index.php?do=evolutionChest.synthetise",
    GetGiftAndOpen: "/index.php?do=item.buyPlusUse",
    EquipmentReinfoce: "/index.php?do=equipment.upgrade",
    EquipmentMultiUpgrade: "/index.php?do=equipment.multiUpgrade",
    SkillUpdate: "/index.php?do=skill.upgradeskillLevel",
    SkillMelt: "/index.php?do=skill.melt",
    SkillMultMelt: "/index.php?do=skill.multiMelt",
    FormulaInfo: "/index.php?do=combat.getUserCombatList",
    PushDataInfo: "/?do=user.getPushData",
    AnnouncementRead: "/index.php?do=menu.notice",
    CombatUpgrade: "/index.php?do=combat.upgradeCombatLevel",
    WishingContent: "/index.php?do=wish.info",
    WishingStart: "/index.php?do=wish.get",
    UnionRankList: "/index.php?do=union.rankList",
    UnionDepotList: "/index.php?do=union.getDepotList",
    UnionShopList: "/index.php?do=union.getGoodsList",
    UnionShopExchangeGoods: "/index.php?do=union.exchangeGoods",
    ApplyList: "/index.php?do=union.applyList",
    UnionUserList: "/index.php?do=union.userList",
    ApplyOperation: "/index.php?do=union.manage",
    Apply: "/index.php?do=union.apply",
    GeneralTrainingInfo: "/index.php?do=training.trainingInfo",
    GeneralTrainingThankYou: "/index.php?do=training.training",
    GeneralOneStepTrainingThankYou: "/index.php?do=training.multiTraining",
    GeneralInsight: "/index.php?do=general.insight",
    SoulReincarnate: "/index.php?do=general.reincarnate",
    EvolutionOpen: "/index.php?do=evolution.open",
    EvolutionChangeYuanFen: "/index.php?do=evolution.changeFate",
    WorshipGeneral: "/index.php?do=general.sacrifice",
    AdventureMake: "/index.php?do=meeting.meeting",
    ClimbLadderStartInfo: "/index.php?do=tower.towerInfo",
    ArtifactStoreyExchangeList: "/index.php?do=tower.towerExchangeList",
    ArtifactStoreyExchangeEquipment: "/index.php?do=tower.towerExchange",
    ClimbLadderStartFightOrSelectInfo: "/index.php?do=tower.towerFightBefore",
    ClimbLadderStartFight: "/index.php?do=tower.towerFight",
    ClimbLadderProperty: "/index.php?do=tower.towerBeStronger",
    ClimbLadderStartFightPass: "/index.php?do=tower.towerFightPass",
    LadderOriginalData: "/index.php?do=ladder.init",
    LadderFight: "/index.php?do=ladder.fight",
    LadderTenFight: "/index.php?do=ladder.repeatedlyFight",
    ChaosSkillPiece: "/index.php?do=warlord.warlordPieceInfo",
    ChaosInfo: "/index.php?do=warlord.warlordInfo",
    ChaosFight: "/index.php?do=warlord.warlord",
    WarLordSkillList: "/index.php?do=warlord.warlordSkillList",
    WarLordExchangeSkill: "/index.php?do=warlord.warlordExchangeSkill",
    OneStepSkillCompose: "/index.php?do=warlord.warlordBatchExchangeSkill",
    SaveUserSign: "/index.php?do=user.chgSign",
    ChangeUserName: "/index.php?do=user.chgNickname",
    GetMail: "/index.php?do=email.getList",
    GetRankList: "/index.php?do=rank.getRankList",
    LikeRank: "/index.php?do=rank.like",
    GetMailAttach: "/index.php?do=email.accept",
    AtlasList: "/index.php?do=atlas.getList",
    GetSurrenderList: "/index.php?do=atlas.getSurrenderList",
    ExchangeCDKey: "/index.php?do=menu.userCdkey",
    FriendApply: "/index.php?do=relationship.replyRequest",
    FeedBack: "/index.php?do=user.leaveMsg",
    SendMessage: "/index.php?do=email.send",
    GetQuasiFriends: "/index.php?do=relationship.userMakeFriendsInfo",
    GetFriends: "/index.php?do=relationship.userFriendsInfo",
    GetFoes: "/index.php?do=relationship.userEnemysInfo",
    FriendRequest: "/index.php?do=relationship.requestFriend",
    DeleteFriend: "/index.php?do=relationship.delUserRelationship",
    SearchUser: "/index.php?do=relationship.searchUser",
    GetServerList: "/index.php?do=account.index",
    QuickBuy: "/index.php?do=item.quickBuy",
    RemoveObject: "/index.php?do=general.removeObject",
    OtherPlayerData: "/index.php?do=general.getOverview",
    InterOtherPlayerData: "/index.php?do=ladderWar.getOverview",
    LocalInterOtherPlayerData: "/index.php?do=ladderWarLocal.getOverview",
    GeneralSelect: "/index.php?do=user.chooseTeam",
    ChargeItemList: "/index.php?do=product.getList",
    CreateOrder: "/index.php?do=product.createOrder",
    PostPaySucessNotify: "/index.php?do=product.notify",
    CheckTransactionReceipt: "/index.php?do=payIos.iosCharge",
    CheckPayStatus: "/index.php?do=product.checkOrder",
    RefineEquip: "/index.php?do=equipment.refine",
    GetMessage: "/index.php?do=chat.getMessage",
    sendMessage: "/index.php?do=chat.send",
    BindingBFAccount: "/index.php?do=account.bindWithBf",
    BindingFBAccount: "/index.php?do=account.bindWithFacebook",
    BindingEasyAccount: "/index.php?do=account.bindWithEasysdk",
    RecordPhoneNum: "/index.php?do=account.chgAccountInfo",
    GetIsWanPuActiveFromServer: "/?do=notify.activate",
    GeTuiSave: "/index.php?do=user.save",
    applyUnionWar: "?do=unionWar.signUp",
    getUnionInfo: "/?do=union.info",
    chgUnionNotice: "/?do=union.chgNotice",
    chgUnionSign: "/?do=union.chgSign",
    exitUnion: "/?do=union.quite",
    createUnion: "/?do=union.create",
    getDonateInfo: "/?do=union.donateInfo",
    donate: "/?do=union.donate",
    taskGetList: "?do=task.getList",
    taskMultiRecieve: "?do=task.multiRecieve",
    taskRecieve: "?do=task.recieve",
    activateBuddyPosition: "?do=buddy.activatePosition",
    setBuddy: "?do=buddy.setBuddy",
    getBattleFormation: "?do=unionWar.getBattleFormation",
    getEncounterInfo: "?do=unionWar.getFightingResult",
    setBattleFormation: "?do=unionWar.setBattleFormation",
    getFightingProcess: "?do=unionWar.getFightingProcess",
    getUnionActvieList: "?do=union.getUnionActiveList",
    getFightingDetails: "?do=unionWar.getFightingDetails",
    friendFight: "?do=relationship.fight",
    allotDepot: "?do=union.allotDepot",
    gemsHoleLock: "?do=gem.lock",
    gemsHoleUnLock: "?do=gem.unlock",
    gemsSophistication: "?do=gem.chgProperty",
    gemsInset: "?do=gem.gemInset",
    gemsRemove: "?do=gem.gemRemove",
    gemInherit: "?do=gem.gemInherit",
    gemsPunch: "?do=gem.bore",
    InterServiceMainInfor: "/index.php?do=ladderWar.entry",
    InterPointsExchangeList: "?do=ladderWar.goodsList",
    InterPointsExchange: "?do=ladderWar.exchange",
    InterBuyFightTimes: "?do=ladderWar.buyFtimes",
    InterGetMatchs: "?do=ladderWar.match",
    worshipEntry: "?do=ladderWar.worshipEntry",
    worship: "?do=ladderWar.worship",
    rewardList: "?do=ladderWar.rewardList",
    buyReward: "?do=ladderWar.buyReward",
    hangReward: "?do=ladderWar.hangReward",
    InterServiceFight: "?do=ladderWar.fight",
    LocalInterServiceMainInfor: "/index.php?do=ladderWarLocal.entry",
    LocalInterPointsExchangeList: "?do=ladderWarLocal.goodsList",
    LocalInterPointsExchange: "?do=ladderWarLocal.exchange",
    LocalInterBuyFightTimes: "?do=ladderWarLocal.buyFtimes",
    LocalInterGetMatchs: "?do=ladderWarLocal.match",
    LocalworshipEntry: "?do=ladderWarLocal.worshipEntry",
    Localworship: "?do=ladderWarLocal.worship",
    LocalrewardList: "?do=ladderWarLocal.rewardList",
    LocalbuyReward: "?do=ladderWarLocal.buyReward",
    LocalhangReward: "?do=ladderWarLocal.hangReward",
    LocalInterServiceFight: "?do=ladderWarLocal.fight",
    gemsCompose: "?do=gem.gemCompose",
    OpenMiracleWeapon: "?do=magic.open",
    MiracleWeaponForge: "?do=magic.forge",
    OthersMiracleWeapon: "?do=magic.getOverview",
    DecisiveBattleMainInfor: "?do=worldWar.index",
    DecisiveBattleSupportRank: "?do=worldWar.supportRank",
    DecisiveBattleSupportRecord: "?do=worldWar.supportList",
    DecisiveBattlePointsExchangeList: "?do=worldWar.goodsList",
    DecisivePointsExchange: "?do=worldWar.exchange",
    DecisiveOtherPlayerData: "?do=worldWar.getOverview",
    DecisiveGetPlayerList: "?do=worldWar.getPlayerList",
    DecisiveGetOverview: "?do=worldWar.getOverview",
    DecisiveSupportPlayer: "?do=worldWar.supportPlayer",
    DecisiveTop128: "?do=worldWar.outline",
    DecisiveViewingFight: "?do=worldWar.getFightDetail",
    DecisiveRefreshTeam: "?do=worldWar.signUp",
    LocalDecisiveBattleMainInfor: "?do=worldWarLocal.index",
    LocalDecisiveBattleSupportRank: "?do=worldWarLocal.supportRank",
    LocalDecisiveBattleSupportRecord: "?do=worldWarLocal.supportList",
    LocalDecisiveBattlePointsExchangeList: "?do=worldWarLocal.goodsList",
    LocalDecisivePointsExchange: "?do=worldWarLocal.exchange",
    LocalDecisiveOtherPlayerData: "?do=worldWarLocal.getOverview",
    LocalDecisiveGetPlayerList: "?do=worldWarLocal.getPlayerList",
    LocalDecisiveGetOverview: "?do=worldWarLocal.getOverview",
    LocalDecisiveSupportPlayer: "?do=worldWarLocal.supportPlayer",
    LocalDecisiveTop128: "?do=worldWarLocal.outline",
    LocalDecisiveViewingFight: "?do=worldWarLocal.getFightDetail",
    LocalDecisiveRefreshTeam: "?do=worldWarLocal.signUp",
    GoddessGoToFight: "?do=godness.fight",
    GoddessCancelToFight: "?do=godness.cancelFight",
    GoddessChangeSkin: "?do=godness.switchGodness",
    HulaoMain: "?do=hulao.index",
    HulaoRecieve: "?do=hulao.recieve",
    HuLaoBattleLineUp: "?do=hulao.lineup",
    HuLaoBattleGoToFight: "?do=hulao.fight",
    MysteryStoreInfo: "/?do=mystery.info",
    MysteryStoreUpdate: "/?do=mystery.refresh",
    MysteryStoreConvert: "/?do=mystery.buy",
    JiFenDuiHuanList: "/?do=festival.getScoreList",
    YuLuList: "/?do=festival.getRainDewList",
    JiFenDuiHuanConvert: "/?do=festival.scoreBuy",
    YuLuConvert: "/?do=festival.getGift",
    SpiritStoneList: "/?do=spiritStoneGoods.getList",
    SpiritStoneConvert: "/?do=spiritStoneGoods.buy",
    AutoPractice: "?do=general.autoCultivate",
    changeGeneralSkin: "?do=user.chgGeneralskin",
    getMultiLineUpInfor: "?do=team.getMostTeamInfo",
    UnlockOneTeam: "?do=team.addTeamInfo",
    SaveOneTeamInfor: "?do=team.saveTeamInfo",
    LoadOneTeamInfor: "?do=team.loadTeamInfo",
    getMeridiansMainInfo: "?do=pulse.getList",
    practiceMeridians: "?do=pulse.practicePulse",
    collectMeridians: "?do=pulse.pulseCollect",
    lightMeridian: "?do=meridian.light",
    multiLightMeridian: "?do=meridian.multiLight",
    AutonymApprove: "/index.php?do=idcard.save",
    SMSAuthenticationCode: "/?do=idcard.getCode",
    SaveMoblieTel: "/?do=idcard.saveMobile",
    evolutionChestGetList: "?do=evolutionChest.getList",
    evolutionChestOpen: "?do=evolutionChest.open",
    evolutionChestOpenTen: "?do=evolutionChest.openTen",
    evolutionChestRefresh: "?do=evolutionChest.refresh",
    evolutionActive: "?do=evolution.active",
    GeneralPreviewList: "?do=wine.wineGeneralInfo",
    beautyInit: "/?do=beauty.init",
    beautySatrt: "/?do=beauty.beautyCruise",
    beautyEnd: "/?do=beauty.beautyCruiseOver",
    beautyAddExp: "/?do=beauty.addBeautyExperience",
    beautyExchangeList: "/?do=beauty.getBeautyExchangeList",
    beautyExchange: "/?do=beauty.beautyExchange",
    skillRefine: "/?do=skillRefine.skillRefine"
});
// source line 631, bytecode pc 2750
(xs.setServerAddrsMap = function(mId) {
    var m_productId, mPorName;
    // source line 632, bytecode pc 22
    (m_productId = (mId || xs.app_indentify));
    // source line 634, bytecode pc 49
    cc.log(("xs.setServerAddrsMap " + m_productId));
    if ((m_productId == xsc.Const_Proj_Code_Develop)) {
        // source line 657, bytecode pc 200
        (xs.Cfg.Url.ServerAddrsMap = {
    NormalServer: { domain: "203.88.162.96:8081/test/sanguosha_account" },
    PublicTip: { domain: "203.88.162.96:8081/test/sanguosha_account" },
    Clock: { domain: "203.88.162.96:8081/test/sanguosha_account" },
    WanPu: { domain: "wypwd.sanguosha.com/public/wanpu" },
    GeTui: { domain: "wypwd.sanguosha.com/public/getui" }
});
    } else {
        if (((m_productId == xsc.Const_Proj_Code_TestOnline) || ((m_productId == xsc.Const_Proj_Code_226_TestOnline) || (m_productId == xsc.Const_Proj_Code_226_BanShu)))) {
            // source line 686, bytecode pc 396
            (xs.Cfg.Url.ServerAddrsMap = {
    NormalServer: { domain: "10.225.254.113/test/sanguosha_account" },
    PublicTip: { domain: "10.225.254.113/test/sanguosha_account" },
    Clock: { domain: "10.225.254.113/test/sanguosha_account" },
    WanPu: { domain: "wypwd.sanguosha.com/public/wanpu" },
    GeTui: { domain: "10.225.254.113/test/getui" }
});
        } else {
            if ((m_productId == xsc.Const_Proj_Code_226_TW_TestOnline)) {
                // source line 712, bytecode pc 552
                (xs.Cfg.Url.ServerAddrsMap = {
    NormalServer: { domain: "203.88.162.96:8081/test/sanguosha_account" },
    PublicTip: { domain: "203.88.162.96:8081/test/sanguosha_account" },
    Clock: { domain: "203.88.162.96:8081/test/sanguosha_account" },
    WanPu: { domain: "wypwd.sanguosha.com/public/wanpu" },
    GeTui: { domain: "10.225.254.113/test/getui" }
});
            } else {
                // source line 718, bytecode pc 587
                (mPorName = xsc.Tools.ProductSys.getArea());
                if ((mPorName == xsc.Const_Area_TW)) {
                    // source line 740, bytecode pc 738
                    (xs.Cfg.Url.ServerAddrsMap = {
    NormalServer: { domain: "cqoverwypwd.sanguosha.com/public/sanguosha_account" },
    PublicTip: { domain: "cqoverwypwd.sanguosha.com/public/sanguosha_account" },
    Clock: { domain: "cqoverwypwd.sanguosha.com/public/sanguosha_account" },
    WanPu: { domain: "wypwd.sanguosha.com/public/wanpu" },
    GeTui: { domain: "wypwd.sanguosha.com/public/getui" }
});
                } else {
                    if ((mPorName == xsc.Const_Area_CN)) {
                        // source line 764, bytecode pc 894
                        (xs.Cfg.Url.ServerAddrsMap = {
    NormalServer: { domain: "wypwd.sanguosha.com/public/sanguosha_account" },
    PublicTip: { domain: "wypwd.sanguosha.com/public/sanguosha_account" },
    Clock: { domain: "wypwd.sanguosha.com/public/sanguosha_account" },
    WanPu: { domain: "wypwd.sanguosha.com/public/wanpu" },
    GeTui: { domain: "wypwd.sanguosha.com/public/getui" }
});
                    } else {
                        // source line 769, bytecode pc 922
                        xs.error("no find project name!");
                    }
                }
            }
        }
    }
});
// source line 775, bytecode pc 2767
xs.setServerAddrsMap();
