APP_STL := gnustl_static
NDK_TOOLCHAIN_VERSION := 4.9
APP_ABI := armeabi-v7a
APP_PLATFORM := android-21
APP_CPPFLAGS := -frtti -DCOCOS2D_JAVASCRIPT=1
APP_CPPFLAGS += -DCOCOS2D_DEBUG=1 -DCC_ENABLE_CHIPMUNK_INTEGRATION=1
