#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
SDK_ROOT="${ANDROID_SDK_ROOT:-${ANDROID_HOME:-/home/inkbottle/Android/Sdk}}"
PLATFORM="${ANDROID_PLATFORM:-android-37.0}"
BUILD_TOOLS="${ANDROID_BUILD_TOOLS:-36.0.0}"
PLATFORM_DIR="$SDK_ROOT/platforms/$PLATFORM"
TOOLS_DIR="$SDK_ROOT/build-tools/$BUILD_TOOLS"
ANDROID_JAR="$PLATFORM_DIR/android.jar"
NATIVE_SO="$SCRIPT_DIR/libs/armeabi-v7a/libcocos2djs.so"
WORK="$SCRIPT_DIR/build"
APK_VERSION_CODE="${APK_VERSION_CODE:-723}"
APK_VERSION_NAME="${APK_VERSION_NAME:-9.17.0.94}"
APK_OUTPUT="${APK_OUTPUT:-$SCRIPT_DIR/sgscq-rebuilt.apk}"

# Checkpoint project changes before rebuilding generated/native outputs so a
# failed build still leaves a recoverable Git commit.
"$PROJECT_ROOT/ClientProject/tools/git_checkpoint.sh" "build: automatic pre-build backup"

# Rebuild the C++/JSB library from this source tree for every APK build.
# Packaging an older library previously hid freshly added native bindings.
"$SCRIPT_DIR/build_native.sh" "-j${NATIVE_JOBS:-4}"

for tool in javac java keytool; do command -v "$tool" >/dev/null || { echo "missing tool: $tool" >&2; exit 2; }; done
for file in "$ANDROID_JAR" "$TOOLS_DIR/aapt" "$TOOLS_DIR/d8" "$TOOLS_DIR/zipalign" "$TOOLS_DIR/apksigner" "$NATIVE_SO"; do
    test -f "$file" || { echo "missing build input: $file" >&2; exit 2; }
done

rm -rf "$WORK"
mkdir -p "$WORK/classes" "$WORK/dex" "$WORK/zip/lib/armeabi-v7a"

python3 "$PROJECT_ROOT/ClientProject/tools/stage_reconstructed_sources.py"
python3 "$PROJECT_ROOT/ClientProject/tools/stage_apk_assets.py" "$WORK/assets"

# Compile this project's clean entry plus the upstream Cocos Android support layer.
mapfile -t JAVA_SOURCES < <(find "$SCRIPT_DIR/src" -type f -name '*.java' | sort)
javac -encoding UTF-8 -source 8 -target 8 -bootclasspath "$ANDROID_JAR" -d "$WORK/classes" "${JAVA_SOURCES[@]}"
mapfile -t CLASS_FILES < <(find "$WORK/classes" -type f -name '*.class' | sort)
"$TOOLS_DIR/d8" --min-api 21 --lib "$ANDROID_JAR" --output "$WORK/dex" "${CLASS_FILES[@]}"

# Package the cleaned project assets. Legacy channel SDK jars/configs are not copied here.
"$TOOLS_DIR/aapt" package -f \
    -M "$SCRIPT_DIR/AndroidManifest.xml" \
    -S "$SCRIPT_DIR/res" \
    -I "$ANDROID_JAR" \
    -A "$WORK/assets" \
    --min-sdk-version 21 --target-sdk-version 28 \
    --version-code "$APK_VERSION_CODE" --version-name "$APK_VERSION_NAME" \
    -F "$WORK/app-unsigned.apk"

cp "$WORK/dex/classes.dex" "$WORK/classes.dex"
cp "$NATIVE_SO" "$WORK/zip/lib/armeabi-v7a/libcocos2djs.so"
(cd "$WORK" && "$TOOLS_DIR/aapt" add app-unsigned.apk classes.dex >/dev/null)
cd "$WORK/zip"
"$TOOLS_DIR/aapt" add "$WORK/app-unsigned.apk" lib/armeabi-v7a/libcocos2djs.so >/dev/null

KEYSTORE="$SCRIPT_DIR/rebuild-debug.keystore"
if [[ ! -f "$KEYSTORE" ]]; then
    keytool -genkeypair -keystore "$KEYSTORE" -storepass android -keypass android \
        -alias sgscq-rebuild -keyalg RSA -keysize 2048 -validity 10000 \
        -dname "CN=SGSCQ Reconstruction, OU=Local, O=Local, C=CN" >/dev/null 2>&1
fi

"$TOOLS_DIR/zipalign" -f 4 "$WORK/app-unsigned.apk" "$WORK/sgscq-rebuilt-aligned.apk"
"$TOOLS_DIR/apksigner" sign --ks "$KEYSTORE" --ks-pass pass:android --key-pass pass:android \
    --out "$APK_OUTPUT" "$WORK/sgscq-rebuilt-aligned.apk"
"$TOOLS_DIR/apksigner" verify --verbose "$APK_OUTPUT"
python3 "$PROJECT_ROOT/ClientProject/tools/verify_client_apk.py" "$APK_OUTPUT"
echo "Built: $APK_OUTPUT"

# Capture any source files regenerated by the successful build as well.
"$PROJECT_ROOT/ClientProject/tools/git_checkpoint.sh" "build: automatic post-build backup"
